name: doormer
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: 3.27.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^3.0.7
  

  flutter_bloc:
  dio:
  get_it:
  font_awesome_flutter:
  flutter_screenutil:
  equatable:
  logger: ^1.3.0
  go_router:
  flutter_secure_storage: ^9.2.4
  test: ^1.25.7
  bloc_test: ^9.1.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  universal_html:
  google_sign_in: 
  google_sign_in_web:
  file_picker:
  dartz:
  google_sign_in_platform_interface: 
  dropdown_button2: ^2.3.9
  flutter_dotenv:
  flutter_markdown: 
  flutter_html:
  toastification:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.6
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/mock/mock_login_response.json
    - assets/candidate_registration_options/candidate_registration_options.json
