name: Trigger auto deployment for taka-dev-1-fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/taka-dev-1-fe-AutoDeployTrigger-7da49b2e-ae3c-49ad-88b8-a03cfa819e84.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TAKADEV1FE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TAKADEV1FE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TAKADEV1FE_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name takadev1acr

      - name: Build and Push Docker Image
        run: |
          docker build -t takadev1acr.azurecr.io/taka-dev-1-fe:${{ github.sha }} -f Dockerfile .
          docker push takadev1acr.azurecr.io/taka-dev-1-fe:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: taka-dev-1-fe
          resourceGroup: taka-dev
          registryUrl: takadev1acr.azurecr.io
          registryUsername: ${{ secrets.TAKADEV1FE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TAKADEV1FE_REGISTRY_PASSWORD }}
          imageToDeploy: takadev1acr.azurecr.io/taka-dev-1-fe:${{ github.sha }}
          dockerfilePath: Dockerfile

